project:
  type: website
  output-dir: docs
  resources: 
    - "media/**"

website:
  title: "Ruilin Wu"
  navbar:
    background: "#a7d8f0"
    left:
      - text: Home
        file: index.qmd
      - text: Research
        file: research.qmd
      - text: Projects
        file: projects.qmd

format:
  html:
    theme: cosmo
    css: styles.css




